### ISSUE TITLE
Attempting to Login will display Username and Password in clear text

### ISSUE THREAD

**Issue by OrangeFlare** [HECommunity/HELegacy#3]
When you enter a username and password into the login box this is the url it will redirect to
https://hackerexperience.xyz/login?username={USERNAME}&password={PASSWORD}&keepalive=on
Admitted this is a https connection _BUT_ you should **NEVER** display usernames and passwords in clear text

**Comment by OrangeFlare** [comment]
Also even worse
the domain hackerexperience.xyz isn't owned ( Proof: https://whois.icann.org/en/lookup?name=hackerexperience.xyz )

What this means is that if anyone were to register "hackerexperience.xyz" they could **_EASILY_** steal usernames and passwords

**Comment by AugustoResende** [comment]
I will fix.

**Comment by AugustoResende** [comment]
fixed.
